### ISSUE TITLE
[Suggestion] Dynmap extention faction info should have classes to the HTML

### ISSUE THREAD

**Issue by Josh65-2201** [ToberoCat/ImprovedFaction#192]
**Is your feature request related to a problem? Please describe.**
Currently i carnt customise/remove the elerments since there all the same
![unknown](https://user-images.githubusercontent.com/26977075/178585928-3824af60-0c09-4f87-b777-e09ad7152c65.png)

**Describe the solution you'd like**
Adding classes to what the infomation should be like `Faction name`

**Comment by ToberoCat** [comment]
So if I understood that correctly, I should add a html file that's getting used for all factions, allowing placeholders to access all faction properties.

Only problem I could see there is, because it would be html, you could also use css to style and JavaScript for interactivity, but that may cause issues with dynmap.

Will try it out. If it's a problem for dynmap, I will have to use a custom XML parser

**Comment by Josh65-2201** [comment]
you could proberly just edit whats it already uses just adding class="Name" after the h1/2 header for eatch entry.
like `<h1 class="factionTitle">info</h1>`. dynmap already has support for customising with css and its own javascripts can be edited for functions.

**Comment by Josh65-2201** [comment]
Could try that i took it from the source code

`marker.setDescription("<div><h1 class="factionName">" + faction.getDisplayName() + "</h1><h2 class="factionMotd">Motd: " + faction.getMotd() + "</h2></div>");`

**Comment by ToberoCat** [comment]
Okay, will try to find a way for it
